location="westeurope"
resourceGroup_name="RG-SAP-Dev"
vnet_name= "sap-dev-vnet"
vnet_address_space = "10.10.0.0/16"
sap_front_vm= "CORP-AZ-FRONT"
sap_app_vm = "CORP-AZ-APP"
admin_password = "Test@123456"
admin_username = "sapadmin"